### PR TITLE
Typescript

### LINKED ISSUE #10: TypeScript 지원

### PR DESCRIPTION
**Pull request by Bas950**
Tested in HTML and Jest. Still works.
You might want to change the output directory back, this is just what I am used to / prefer. 

closes https://github.com/SDuck4/type-hangul/issues/10

### CODE REVIEW

**Comment by Bas950** [comment]
Something we should look into:
image
If non-korean letters are included in the text those letters take twice as long to display.

**Comment by Bas950** [comment]
Just noticed min.js is not working, maybe you could look into that.

**Comment by SDuck4** [comment]
Thank you for contributing to this library.
I didn't expect to receive other people's PR from foreign countries.
This is a very interesting and exciting experience.

Anyway, I am not familiar with the latest TypeScript and Vue, so the review may take a long time.
I'd appreciate it if you could wait for the review.

**Comment by Bas950** [comment]
> Thank you for contributing to this library.
> I didn't expect to receive other people's PR from foreign countries.
> This is a very interesting and exciting experience.

Hahaha no problem, glad I can help you out!

> Anyway, I am not familiar with the latest TypeScript and Vue, so the review may take a long time.
> I'd appreciate it if you could wait for the review.

I haven't done any vue stuff yet, this PR focuses on the TypeScript part.
Take you time with reviewing!

**Comment by Bas950** [comment]
> If non-korean letters are included in the text those letters take twice as long to display.

Fixed in https://github.com/Bas950/type-hangul/commit/e99dd60d3833f070f9902ba7fc04ddaa3a4bcb50
image
There is still an extra timeout after it finished writing a Korean sentence (this is intentional I think).

**Comment by Bas950** [comment]
Something I haven't checked yet;
But maybe the main in `package.json` needs to be changed to the `index.js` file.

**Pull request closed without merging**
